### ISSUE TITLE
Add mapathon event kind

### ISSUE THREAD

**Issue by qeef** [thomersch/openstreetmap-calendar#10]
I started to use the osmcal.org for organizing Missing Maps mapathons. It would be nice to have the corresponding event kind. I am hesitating to organize mapathons as map events.

**Comment by thomersch** [comment]
I see your issue – I am not happy with the categories either, just transferred them from the wiki for a smoother transition, but I struggle to classify many events into those groups. And since the OSM community is so multi-cultural, people have very different understandings of those labels.

Currently, the option is there and saved into the database, but actually never displayed (not even through the API). I could, of course, easily add "Mapathon" to the list of possible categories, but I'd rather reconsider the whole concept.

**Comment by qeef** [comment]
I think that categories should be community decided. Neither I am able to say "these categories area right, add them".

But it's easy to add categories at wiki, I just added mapathon category (https://wiki.openstreetmap.org/wiki/Template:Calendar#How_to_update_the_calendar) and happily using it.

> but I'd rather reconsider the whole concept.

I am not sure what you mean by reconsidering the whole concept. Will you remove categories?

**Comment by qeef** [comment]
I guess I can close this and continue discussion on #36.
