### ISSUE TITLE
Add share button for social media

### ISSUE THREAD

**Issue by qeef** [thomersch/openstreetmap-calendar#12]
To simplify event sharing on social media networks, add a corresponding share button.

**Comment by thomersch** [comment]
We'd have to decide which networks to use, build some buttons for those, check the respective trademark policies and in the end, at least in my experience, no one really uses them, because people who are very into social media already have some browser extensions or are using a specific client (e.g. Tweetdeck) to manage their social media presence.

osmcal already has opengraph meta tags which make some nicely looking social media URL boxes.

**Comment by qeef** [comment]
Well, I don't use social media much, just care about sharing the event with friends as easily as possible. I understand the answer as "there is already this utility implemented differently", therefore closing the issue. Thanks :)
