### ISSUE TITLE
Add presential/online categories + training as type of event + language

### ISSUE THREAD

**Issue by severinmenard** [thomersch/openstreetmap-calendar#123]
Some suggestions to make it easier to find specific interests in the calendar:

- add a category presential/remote to make this aspect clear

- in "Kind" add workshop and/or training  among the available options

- a new category for the language(s) used during the event

**Comment by danieldegroot2** [comment]
Hey severinmenard,

Thanks for your feedback. I'm a user, not the dev, but I'll reply to your points below;

> add a category presential/remote to make this aspect clear

This is intentionally left out, as it is redundant. You may use the Location field for this instead. You can specify this as "Virtual" or "Online". On WeeklyOSM entries, this will add a ✔️ tick [to the online column](https://weeklyosm.eu/archives/16366) (scroll down to the calendar at the bottom) - adding any text after these keywords, e.g. " (Zoom)" should not matter for the tick. If you do not mind losing this tick, you can specify whatever you like, i.e. "Presential", "Remote", ...
You will need to specify the timezone manually in this case. (If it is Universal Time, "UTC", scroll down to the bottom of the list.).

> in "Kind" add workshop and/or training among the available options

This mainly falls under the categories "Social" (a relaxed activity which may include mapping) or "Mapping event" (any activity which includes mapping). You can explain it is a workshop in the description, or on the event website.
Otherwise, this is a known suggestion, discussed in #7. (tldr: The calendar was previously hosted on the wiki. Its categories have been re-used for this calendar, but are unclear to some people. The developer has been considering to change this feature.)

> a new category for the language(s) used during the event

You may indicate the languages used in the description, or on the event website. It is good practice to write your event description in the available languages where possible. You could also ask what language participants want to / will speak by adding a survey form to your event.
Most events are of a single language, usually the most commonly spoken language in a country. Also, in some countries people are willing to adapt to speakers of other languages.<sup>([from 'add flag icons'](https://github.com/thomersch/openstreetmap-calendar/issues/46#issuecomment-707158776))</sup> Therefore this feature may be considered to be of low priority.

Related issues are being discussed in #53 (translation of the website interface), #22 (translation of event descriptions) respectively.

**Comment by thomersch** [comment]
Thanks for summarizing, @danieldegroot2 

@severinmenard Feel free to comment on the linked issues, but please be aware that I currently don't have much time for new developments
