### ISSUE TITLE
Allow specifying time zone of an event

### ISSUE THREAD

**Issue by 1ec5** [thomersch/openstreetmap-calendar#13]
Thanks for adding a way to specify the time of an event! It would be helpful if users could also indicate the time zone, especially for online events. Otherwise, users have to assume a time zone based on the location, but they might instead assume their own time zone.

Similarly, it would be neat if the times could be converted to the user’s local timezone automatically or based on an option.

**Comment by thomersch** [comment]
That is a problem I wanted to avoid but you're right: For online events there is no "local time zone".

We just have to figure out a interface so that users don't get confused when adding new events. Almost all events have an unambiguous local timezone, except for a few, so I would want to make it as subtle as possible.

**Comment by thomersch** [comment]
fyi: Work on this issue is part of my OSMF microgrant proposal: https://wiki.openstreetmap.org/wiki/Microgrants/Microgrants_2020/Proposal/OpenStreetMap_Calendar

**Comment by qeef** [comment]
I think that it make sense to make timezone the same as the location of the event.

**Comment by thomersch** [comment]
Things have happened: There is now a field for specifying a time zone, if necessary. Time zone info is exposed in the API (v2), the iCalendar feeds and in textual representations for all location-free events.

If I got some spare time, I‘ll add automatic time zone conversion for logged-in users.
