### ISSUE TITLE
Deleting location partially broken

### ISSUE THREAD

**Issue by Mannivu** [thomersch/openstreetmap-calendar#153]
When deleting the location of the event, the location is still visible under the event's title. See this example ([this event](https://osmcal.org/event/2607/))

![image](https://github.com/thomersch/openstreetmap-calendar/assets/42747216/8ee0eaa0-013d-4788-bf9e-a5974a9c1e81)
It's set in Avigliano Umbro, Umbria, Italy as you can read under the title. But if I delete the location

Before
![Before](https://github.com/thomersch/openstreetmap-calendar/assets/42747216/37d3e5a8-6f9a-439e-a4bd-112b6d1d709b)

After
![After](https://github.com/thomersch/openstreetmap-calendar/assets/42747216/f827f99b-3659-4b23-a5b0-8288a7844ea8)

The location is still visible under the title, but the minimap is gone
![image](https://github.com/thomersch/openstreetmap-calendar/assets/42747216/ff4d7013-1bdb-46c4-8a99-cd302ba9ae25)

**Comment by danieldegroot2** [comment]
Hey @Mannivu,

Thanks for the issue. It is still a bit rough, as is the date and timezone selection.
For convenience, I've created a [new event](https://osmcal.org/event/2617/) and hidden [the old one](https://osmcal.org/event/2607/) (it will not appear in the list anymore).

Fyi, this issue is not limited to OSMCal, I have seen it elsewhere too.
I am a moderator for this website, not the developer. It may take some time for them to reply. Please be patient.

**Comment by thomersch** [comment]
This should be resolved now, as the geocoded location is deleted on save, in case there is no location anymore.
