### ISSUE TITLE
When does the RSS gets the information?

### ISSUE THREAD

**Issue by natrius** [thomersch/openstreetmap-calendar#169]
https://osmcal.org/documentation/
There is nothing there abot when the feed should get out. I subscribed to austria via https://osmcal.org/events.rss?in=Austria in our Matrix-Channel https://matrix.to/#/#osm-at:matrix.org a month ago or something like that and tomorrow there is a event https://osmcal.org/event/2421/ and its in the the rss file but i do not get a response. 

Or is this just to get an information when a new event is added in austria?

**Comment by thomersch** [comment]
To summarise what we have talked in chat:

The RSS feed publishes new events right away, it means that you can stay updated about new events, no matter when they take place.

#osm-at:matrix.org wanted a way to get events that are happening in the near future, that's why I have introduced a new parameter for feeds: `days`. If you add it to an RSS URL, e.g. `https://osmcal.org/events.rss?in=at&days=7` the feed will only contain events that are happening in the next 7 days.
