### ISSUE TITLE
Relation to Template:Calendar in the wiki?

### ISSUE THREAD

**Issue by westnordost** [thomersch/openstreetmap-calendar#20]
I am a bit confused about this, so far I thought the place to contribute events to is https://wiki.openstreetmap.org/wiki/Template:Calendar

As far as I know, weeklyOSM does parse that wiki page as well.

Can you clarify the relation of osmcal to that wiki page? Does osmcal automatically include events added on that wiki page? And/or does osmcal add events to that wiki page that haven't been added there yet but in osmcal? Apart from https://osmcal.org/ , who uses the data from osmcal? (For example, I think weeklyOSM uses the data from that wiki page) Is the goal to replace the wiki page and maybe even include this software on openstreetmap.org? If yes, is there some kind of migration plan?
Finally, what made it necessary to develop this calender, what does it do better than that wiki page?

(Maybe the answers can go into the readme as well)

**Comment by thomersch** [comment]
We made OSMCAL, because the Wiki has some usability problems: Editing the lists is not very approachable, especially for people on small devices or the inexperienced. Also, we wanted to have RSS feeds, calendar subscriptions and a proper API. We already have features that aren't available in the wiki.

The wiki is a way of collecting knowledge, but in my impression it falls short for data. We're not collecting our geo data in a wiki either, after all.

There is no automatic exchange of data. We want to be the place to go for events in the future, thus replacing the wiki calendar some day. We want people to switch over themselves instead of importing. Theoretically, this could be on osm.org some day, but there is no ten year plan for that.

I've been talking to people from weeklyOSM and we talked about possibly integrating OSMCAL into weekly, which is the reason I created the API.

**Comment by westnordost** [comment]
Thank you for the clarifications!

I asked because I intend to link the/a calendar from StreetComplete, but as long as there are two methods in competition I rather wait whether osmcal really replaces the wiki calendar in the future or there is going to be an aggregate feed that combines both.

**Comment by thomersch** [comment]
I haven't heard from anyone that really loves the wiki calendar, so I would want to encourage everyone to switch over and hopefully deprecating the wiki calendar completely. This of course will only work if the calendar has enough of an audience. Our reach is already quite good as people are subscribing using either RSS or iCalendar, but expanding it to get more eyeballs would help tremendously. OSMCAL is very mobile-friendly, so I believe it could be a great match for StreetComplete.

I've been talking about integrating it into more spaces, so my next step is to try to get into the landing pages of the local chapters.
