### ISSUE TITLE
Support for recurring events

### ISSUE THREAD

**Issue by westnordost** [thomersch/openstreetmap-calendar#21]
I think a thing that is currently lacking for the wiki calendar is the ability to create recurring events. Most "Stammtisch" monthly meetings in Germany are at a fixed day in the month, f.e. the second Tuesday each month.

**Comment by thomersch** [comment]
We have been thinking about it, but the models are very different at the moment: Every fourth Thursday, every 28 days, every three month, except...

Also: I don't want to list events that do not exist anymore, but are still in the calendar, because no-one came around to remove them.

So, what we have is the "Repeat Event" function, which makes it super easy to replicate a (past) event from every event page.
