### ISSUE TITLE
Map-View of the actual events

### ISSUE THREAD

**Issue by DerKarlos** [thomersch/openstreetmap-calendar#35]
An OSM-Event Calender "must" have a map, showing the events to easily see what is next to me.
I used ethermap as a [demo](https://getethermap.org/m/snxcjjdmh3jjak3teren). This is done manually. Automatically update this map is not a good way.

osmcal offers a good API to create a leaflet calendar with the actual events on client side.
I could do it, about as I did it with [OSMgo](https://osmgo.org/map/?go=1)
The Javascript could be hosted on osmcal.org/map to be used from anywhere.
I may need some help with github and integrating the map.
Firstly I will make a demo to show you, what I mean.

Later there will be more to decide: How the event and its popup should look alike, what to do with regular events, ...

Warning: I am an software old-timer, no modern coding or tooling. The latest new I learned about software was object orientation.

**Comment by jbelien** [comment]
Hello @DerKarlos ,

I worked in partnership with @thomersch to build OpenStreetMap Calendar widgets.
One of those widgets is a simple map.
You can have a look at it here : https://jbelien.github.io/openstreetmap-calendar-widget/ (repository is [here](https://github.com/jbelien/openstreetmap-calendar-widget)).

I tried to keep those widgets as simple as possible.
Maybe it can fit your needs !

**Comment by thomersch** [comment]
Hi @DerKarlos,

thanks for your inquiry :)

Maybe @jbelien's widget can already help you out. I didn't want to have a worldwide map as a central entry point to the calendar, because it will always look like this:

<img width="546" alt="Screenshot 2020-06-12 at 11 46 05" src="https://user-images.githubusercontent.com/948605/84489669-5214dd80-aca2-11ea-9ccd-41034e1e8f66.png">

_By which I mean: a big cluster of events in Europe and the US, some in Asia._

For regional communities it might be useful to users, because they will look what is going on nearby.

**Comment by DerKarlos** [comment]
@ jbelien
> One of those widgets is a simple map.

Widget? A code to dynamically fill a rectangle, contained in Web pages. An OSM event map in your case.
That's quite what I intended!

We could think about more features, like this:
* There are categories in the [wiki](https://wiki.openstreetmap.org/wiki/Current_events) I don't see them in https://osmcal.org/ or in its API.
The symbols could be used instead of the blue needles
* needle size according to the time left to the event?
* How tho handle clusters (A number instead of crowded needles)

But that are just details and not _as simple as possible_.
The other question is where to use, to see the map.
I could image a link to the map or the widget
always if there is a list of the events (wiki, https://osmcal.org/, weekly-osm)

-------------------

@thomersch I think, I know you from another place, don't I?  Mastodon?

My version looks a bit less empty but equal clustered:
<img width="368" alt="Screenshot 2020-06-12 at 21 06 06" src="https://user-images.githubusercontent.com/1619669/84537863-dbeb9780-acf0-11ea-94ee-75fa3eebca9a.png">
We could use the users IP to detect its location and just show the local "cluster" spread.
A mosaic of clusters? No, far to complicated.

It is just because I feel about OSM as a map, always.
And always when I saw the event list in the Weekly-OSM,
I am missing a map.

**Comment by jbelien** [comment]
> Widget? A code to dynamically fill a rectangle, contained in Web pages. An OSM event map in your case.
> That's quite what I intended!

Exactly what is is !

And indeed it could be improved !
5 event "types" are defined but not available (yet) in the API (ping @thomersch)

**Comment by thomersch** [comment]
>  I think, I know you from another place, don't I? Mastodon?

I think we were discussing some ideas about vector tiles and pipelines a while ago.

> 5 event "types" are defined but not available (yet) in the API (ping @thomersch)

To be honest, I wanted to remove those altogether, because they’re too broad and it’s really difficult to decide what kind of event fits best. I always struggled when creating an event. Also, the cultural differences are too broad. (see #10)

Frankly, I don’t really see users searching based on that criteria. People, who are novices, want an event that is really close by, because they don’t want to travel far. People, who know a specific kind of event (e.g. Hackweekend Karlsruhe, SotM) are interested in exactly those repeated events.

I want to solve the grouping of events through the more flexible concept of communities, which has a prototype, but still needs work. Subscribe to #36, there will be more info soon.

> And always when I saw the event list in the Weekly-OSM

The aim of my microgrant is to integrate osmcal into weekly, but we will have to talk with the weekly team about the specific and what they want. The preview for the upcoming week could totally make sense as a small map.

**Comment by DerKarlos** [comment]
We can agree about categories (I am personally not that happy with the icons anyway).

What about "online"? That could be a relevant boolean criteria to osmcal,the API, the list&map(needle color?).
In Corona times, also local meetings are online, so they still have a needle. But some are just "world". I would place them in the center of the Atlantic.

So the map is coming, fine. I will watch the progress and send feedback. Tell me if I can help -karlos-

**Comment by jbelien** [comment]
I agree that the category are not really useful (won't ever fit every needs).

I like the online/IRL boolean idea !

**Comment by thomersch** [comment]
As we discussed, the [awesome widget](https://jbelien.github.io/openstreetmap-calendar-widget/) has a map view, so I'll close this issue for now.
