### ISSUE TITLE
OSM ID Field for Location

### ISSUE THREAD

**Issue by urbanhop** [thomersch/openstreetmap-calendar#8]
... it would make it a real opensteetmapcalendar. i think the information that @jbelien collects for the location is perfect:

    location:
       name: Cafe De Markten
       address: Rue du Vieux Marché aux Grains / Oude Graanmarktstraat 5 - 1000 Brussels
       osm: https://www.openstreetmap.org/node/870247035
       longitude: 4.3467468
       latitude: 50.8504401

https://github.com/osmbe/website/blame/master/_events/en/2019-10-15-meeting-brussels.md#L7

osm would be optional and might not always be available, but most time.

**Comment by thomersch** [comment]
I don't really see the benefit. We do have a full location, it can even be further described. The OSM ID on the other side is not something that is well designed for such purposes: It can change at any time (e.g. object has been a node and is now a way) and doesn't provide any useful information without having to query OSM.

We already have lat/lon, we do have the reverse geocoding result and we allow for a verbal description of the venue. Is there something at a usability level that you miss?

**Comment by jbelien** [comment]
I use it to have a direct link to the object (location + details).

But you're absolutely right about the fact the id is not stable and so, I can have broken links.

**Comment by urbanhop** [comment]
Usability of the UI is perfectly fine. Nice on IPad, nice on desktop. This is about API, the path to the data without UI. I would like to integrate those events in another calendar-based app where I have locations with OSM data. Relating the events via osmid would be much simpler then lat/lon comparison or composing another geocoding request to get the osmid again and relating afterwards.

Your thoughts about osmid fluctuation are certainly valid, the nodes where the events here happen however, like ETH Zürich or the places where meetups are held, have *fairly* good durability. 

I saw that nominatim returns the osmid. If we could just keep that value with the meaning of the historical-geocoding-osmid I would be really happy.

. . . .

In the last millennium the consistency dogma ruled computer science - systems that could not guarantee consistency around the clock would be worthless. Then Tim Berners Lee said "I wont care about broken links, a 404 shall be good enough.". A valient move, the WWW is inconsistent by design. This liberation followed fluffy-consistency systems like OSM ("occasional" not "eventual") and we are fine, aren't we?

**Comment by thomersch** [comment]
OSM IDs may not break _all_ the time, but I still don't understand the benefit beyond "because I have this data field". Trying to make sense out of OSM IDs can be quite the challenge, when objects are ways/relations or are already gone or are still there, but have completely changed their meaning. In the case of the Bonn meetup, I would get this result: https://nominatim.openstreetmap.org/details.php?place_id=115692891 This might be technically true, as the event is in this building with this way id, but in reality one of the other nodes would fit better.

If you want to save the OSM ID to your database, feel free to look it up based on lat/lon. I have no better way to determine it either.

Thanks anyway for the discussion.

— Thomas
