### ISSUE TITLE
Error 500 when saving even via Safari

### ISSUE THREAD

**Issue by tordans** [thomersch/openstreetmap-calendar#83]
I just edited https://osmcal.org/event/976/ in safari and got an error 500.

Editing the same event in Chrome worked.
In Safari I tried editing text and add end date+time at the same time. In Chrome I did it in two saves.
I was able to edit/safe the event in safari after editing it in Chrome.

https://osmcal.org/event/976/change/

<img width="673" alt="Bildschirmfoto 2021-11-06 um 09 02 04" src="https://user-images.githubusercontent.com/111561/140602794-2737ec9c-5b4e-4483-b69f-ffe0535fe5dd.png">

**Comment by thomersch** [comment]
Safari is alright, I use it all the time. The issue is that in recent months Nominatim has become less reliable and likes to throw return bad gateway pages. When you save, the location is geocoded, and recently this fails more often, thus a bad gateway page.

I have some code to handle Nominatim hiccups, but I currently don’t have the time to finalize it.
