### ISSUE TITLE
OSM Cal "502 Bad Gateway"

### ISSUE THREAD

**Issue by SK53** [thomersch/openstreetmap-calendar#85]
I'm getting a "bad gateway" message at the site, and the OSM WIki is not displaying any events.

**Comment by thomersch** [comment]
Sorry, broken power supply in the rack triggered the circuit breaker and caused some downtime. The server came back up after that, but PostgreSQL was too shy to restart (“another server might be running“). Since I‘m on vacation it took me a while to get back to a shell.

(For reference: https://twitter.com/osm_events/status/1459155544648953858)
