### ISSUE TITLE
Feature request: Show total pages in Past Event

### ISSUE THREAD

**Issue by LaoshuBaby** [thomersch/openstreetmap-calendar#93]
(Maybe this is a unuseful issue?)

![图片](https://user-images.githubusercontent.com/42690037/155109378-6f72b9a7-3b20-4580-a344-694e5b85a194.png)

When we want to jump to a long time ago, we don't know which number to fill in `https://osmcal.org/events/past/<page>` and how many pages should we pass.

**Comment by thomersch** [comment]
Definitely possible, maybe useful, but realistically I probably won’t implement this, because I‘m too lazy ;)

Sidenote: I‘d rather implement paging for the API, so people could do data analysis if they wish, but since event IDs are sequential, you can enumerate them quickly anyway.

Feel free to open issues for any other ideas you have.
