### ISSUE TITLE
Question: Is SourceSansPro intentionally preloaded?

### ISSUE THREAD

**Issue by danieldegroot2** [thomersch/openstreetmap-calendar#95]
Browser: Chrome

Dev console
![image](https://user-images.githubusercontent.com/67521919/155613929-67e8bcd1-4a67-476d-be3f-2380027c37c1.png)

**Comment by thomersch** [comment]
Yes, it is. Though I am not sure whether that's a wise decision. Preloading can decrease load time, because those assets requests are multiplexed over http/2.

Do you have Source Sans Pro installed on your system? Because then the system one is picked why this message might pop up. Initially I added this mechanism to reduce transfer size if you already got the font, but then I added preload which defeats the purpose of the first mechanism.

Tangentially, I am always a bit torn about custom fonts: They are quite large, thus dragging the first load down. On the other hand, the default fonts on some environments are truly awful, and I want to have more control here.

**Comment by danieldegroot2** [comment]
Doesn't look like it's installed on my system.

Now also mentions request credentials
![image](https://user-images.githubusercontent.com/67521919/155785158-26806274-998a-4772-a463-cbe68cde6e08.png)

**Comment by thomersch** [comment]
I can't make any sense from cross origin. It's coming from exactly the same domain. Also, I cannot reproduce it. Are you running some plugins that might interfere?

The complaint about the preload stuff only appears in Chrome, so I am a bit reluctant to change anything.

**Comment by danieldegroot2** [comment]
> Are you running some plugins that might interfere?

No. I don't have any issues seeing the text or font afaik, I only noticed I got these warnings in the dev console. This is what the site looks like for me (high dpi, can always cause issues ofc).

![image](https://user-images.githubusercontent.com/67521919/155793034-e27c019b-8b4b-496b-8866-af74f0271688.png)
![image](https://user-images.githubusercontent.com/67521919/155793141-bbf706f5-2967-4522-8fd8-4f5f70b44ca2.png)

**Comment by thomersch** [comment]
Apparently, [the w3c mandates the crossorigin attribute on preloaded fonts](https://w3c.github.io/preload/#early-fetch-of-critical-resources), but Chrome seems to enforce this even for same-origin sources. From my reading, the specification mandates this only for CORS, but since this was an easy workaround for Chrome, I quickly pushed this out: 7b39115b88fb391a629236cffbc89ca164f7e290
